import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Welcome.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href='/info'>Zentala.io!</Link>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a
            href="https://cv.zentala.io"
            target='_blank'
            rel="noreferrer"
            className={styles.card}
          >
            <h2>CV &rarr;</h2>
            <p>Me, my skills, experience, employment history.</p>
          </a>

          <a
            href="https://github.com/zentala"
            target='_blank'
            rel="noreferrer"
            className={styles.card}
          >
            <h2>GitHub &rarr;</h2>
            <p>My open source projects and repositories.</p>
          </a>

          <a
            href="https://www.behance.net/pzentala"
            target='_blank'
            rel="noreferrer"
            className={styles.card}
          >
            <h2>Behance &rarr;</h2>
            <p>My old web designs and printables.</p>
          </a>

          <a
            href="/blog"
            className={styles.card}
          >
            <h2>Blog &rarr;</h2>
            <p>
              Thoughts, articles, know-how, felietons
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
